export const LOCATIONS = [
  {
    slug: "e3-vijayawada",
    name: "E3 Vijayawada",
    city: "Vijayawada",
    image: "/gallery/ethree/ethree_8.webp",
    bookingUrl: "https://www.ethree.in/",
    description: "Our flagship entertainment hub in Vijayawada. E3 offers a blend of virtual reality, futuristic gaming, and a premium lounge experience.",
    features: ["VR Gaming", "Holographic Zones", "Luxury Lounge", "Sports Bar"],
    pricing: "Starts from ₹499",
    activities: [
      { name: "VR Thrill", desc: "Advanced VR motion simulators." },
      { name: "Laser Tag", desc: "Multi-player neon arena." },
      { name: "Retro Arcade", desc: "Classic games with a modern twist." },
    ],
  },
  {
    slug: "e4-eluru",
    name: "E4 Eluru",
    city: "Eluru",
    image: "",
    bookingUrl: "https://www.efour-eluru.com/",
    description: "E4 Eluru is the city's largest indoor entertainment and sports arena, designed for families and youth alike.",
    features: ["Indoor Sports", "Gaming Arena", "Family Fun Zone", "Cafe"],
    pricing: "Starts from ₹299",
    activities: [
      { name: "Indoor Turf", desc: "Professional grade mini-football." },
      { name: "Bowling Alley", desc: "Techno-bowling with LED lanes." },
      { name: "Kidz Kingdom", desc: "Safe play area for children." },
    ],
  },
  {
    slug: "rg-park",
    name: "RG Park Vijayawada",
    city: "Vijayawada",
    image: "/gallery/rg_park/rg_park_7.webp",
    bookingUrl: "",
    description: "Rajiv Gandhi Park, revitalized by Jaan Entertainment, offers an outdoor escape with modern amusement attractions.",
    features: ["Themed Gardens", "Musical Fountains", "Outdoor Rides", "Boating"],
    pricing: "Entry: ₹50 | Rides: Additional",
    activities: [
      { name: "Musical Fountain", desc: "Synchronized water and light show." },
      { name: "Paddle Boating", desc: "Relaxing boat rides on the lake." },
      { name: "Mini Train", desc: "Fun ride through the park gardens." },
    ],
  },
];
