export const LOCATIONS = [
  {
    slug: "e3-vijayawada",
    name: "E3 Vijayawada",
    city: "Vijayawada",
    image: "/gallery/ethree/ethree_8.webp",
    bookingUrl: "https://www.google.com/maps?rlz=1C5MACD_enIN1163IN1164&um=1&ie=UTF-8&fb=1&gl=in&sa=X&geocode=KVuKaGRm8TU6MXvighODu933&daddr=Opp.+APSRTC+Bus+Stand,+Padmavathi+Ghat,+Krishnalanka,+Vijayawada,+Andhra+Pradesh+520013",
    description: "Our flagship entertainment hub in Vijayawada. E3 offers a blend of virtual reality, futuristic gaming, and a premium lounge experience.",
    features: ["VR Gaming", "Holographic Zones", "Luxury Lounge", "Sports Bar"],
    pricing: "Starts from ₹499",
    activities: [
      { name: "VR Thrill", desc: "Advanced VR motion simulators." },
      { name: "Laser Tag", desc: "Multi-player neon arena." },
      { name: "Retro Arcade", desc: "Classic games with a modern twist." },
    ],
  },
  {
    slug: "e4-eluru",
    name: "E4 Eluru",
    city: "Eluru",
    image: "/gallery/efour/IMG_8400.JPG",
    bookingUrl: "https://www.google.com/maps/dir//EFOUR,+BUS+STAND,+opp.+NEW+RTC,+Ameenapet,+Eluru,+Andhra+Pradesh+534006/@16.5238431,80.6215903,15z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3a36131a0e74054d:0x366c34d3c0b4589c!2m2!1d81.0889024!2d16.7089304?entry=ttu&g_ep=EgoyMDI2MDUwMi4wIKXMDSoASAFQAw%3D%3D",
    description: "E4 Eluru is the city's largest indoor entertainment and sports arena, designed for families and youth alike.",
    features: ["Indoor Sports", "Gaming Arena", "Family Fun Zone", "Cafe"],
    pricing: "Starts from ₹299",
    activities: [
      { name: "Indoor Turf", desc: "Professional grade mini-football." },
      { name: "Bowling Alley", desc: "Techno-bowling with LED lanes." },
      { name: "Kidz Kingdom", desc: "Safe play area for children." },
    ],
  },
  {
    slug: "rg-park",
    name: "RG Park Vijayawada",
    city: "Vijayawada",
    image: "/gallery/rg_park/rg_park_7.webp",
    bookingUrl: "https://www.google.com/maps?rlz=1C5MACD_enIN1163IN1164&gs_lcrp=EgZjaHJvbWUqDggAEEUYJxg7GIAEGIoFMg4IABBFGCcYOxiABBiKBTIGCAEQRRg5Mg4IAhBFGCcYOxiABBiKBTITCAMQLhivARjHARiRAhiABBiKBTINCAQQABiRAhiABBiKBTIGCAUQRRg9MgYIBhBFGDwyBggHEEUYPNIBBzgwNWowajeoAgCwAgA&um=1&ie=UTF-8&fb=1&gl=in&sa=X&geocode=KTmfZaIf8DU6MbpNneggmoxZ&daddr=NH+65,+Krishnalanka,+Vijayawada,+Andhra+Pradesh+520001",
    description: "Rajiv Gandhi Park, revitalized by Jaan Entertainment, offers an outdoor escape with modern amusement attractions.",
    features: ["Themed Gardens", "Musical Fountains", "Outdoor Rides", "Boating"],
    pricing: "Entry: ₹50 | Rides: Additional",
    activities: [
      { name: "Musical Fountain", desc: "Synchronized water and light show." },
      { name: "Paddle Boating", desc: "Relaxing boat rides on the lake." },
      { name: "Mini Train", desc: "Fun ride through the park gardens." },
    ],
  },
];
